export const AFFILIATES = {
  KAYAK_PARTNERID: process.env.NEXT_PUBLIC_KAYAK_PARTNERID || "DEMO-PARTNER",
  BOOKING_AID: process.env.NEXT_PUBLIC_BOOKING_AID || "1111111",
  AGODA_CID: process.env.NEXT_PUBLIC_AGODA_CID || "2222222",
  EXPEDIA_CAMPAIGN: process.env.NEXT_PUBLIC_EXPEDIA_CAMPAIGN || "expedia-demo-campaign",
  HOTELS_CAMPAIGN: process.env.NEXT_PUBLIC_HOTELS_CAMPAIGN || "hotels-demo-campaign"
};
